$(function(){$(window).scroll(function(){$(this).scrollTop()>400?$(".simplifytotop").addClass('arlniainf'):$(".simplifytotop").removeClass('arlniainf')}),$(".simplifytotop").click(function(){return $("html,body").animate({scrollTop:0},400),!1})});
var scrollTimer = null;$(window).scroll(function() {var viewportHeight = $(this).height(),scrollbarHeight = viewportHeight / $(document).height() * viewportHeight,progress = $(this).scrollTop() / ($(document).height() - viewportHeight),distance = progress * (viewportHeight - scrollbarHeight) + scrollbarHeight / 2 - $('#scroll').height() / 2;$('#scroll').css('top', distance).text(' (' + Math.round(progress * 100) + '%)').fadeIn(100);if (scrollTimer !== null) {clearTimeout(scrollTimer);}scrollTimer = setTimeout(function() {$('#scroll').fadeOut();}, 1500);});
  (function() {
    var dr = document.createElement('script');
    dr.type = 'text/javascript'; dr.async = true;
    dr.src = '//share.donreach.com/buttons.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dr);
  })();
function loadscript(filename) {var scr=document.createElement('script');scr.setAttribute("type","text/javascript");scr.setAttribute("src",filename);document.getElementsByTagName("head")[0].appendChild(scr);}var waitElm=null;function urltinyfyprompt_callback(response) {if(waitElm) waitElm.style.display="none";var txt="Short URL";if(response.title && response.title!="") txt+=' for "'+response.title+'"';else if(response.longurl && response.longurl!="") txt+=" for "+response.longurl;if(response.tinyurl && response.tinyurl!="")prompt(txt+":", response.tinyurl);else alert("Could not get short URL, try again later." + ((response.error && response.error != "") ? ("nError: " + response.error) : ""));}function shortenUrl(elm, long_url, service) {waitElm=elm.parentNode.nextSibling;if(waitElm) waitElm.style.display="inline";loadscript("https://urltinyfy.appspot.com/"+service+"?unify=1&url="+encodeURIComponent(long_url) + "&callback=urltinyfyprompt_callback");}
